### ISSUE TITLE
Not compatible with WG 6

### ISSUE THREAD

**Issue by TheOnlyRealTGS** [mewin/WorldGuard-Region-Events#11]
Gives tons of errors.

**Comment by ZephireNZ** [comment]
@mewin Looks like this just needs to be recompiled with WG 6, no other code changes required. ApplicableRegionSet was converted from a concrete class to an interface, causing bytecode incompatibility.

It probably would be a good idea to check if it's a RegionResultSet, as that's the concrete class that's actually returned (most of the implementing classes won't have an 'applicable' field.

**Comment by ZephireNZ** [comment]
And in fact, that section of the code can be cleaned up: the new ApplicableRegionSet interface defines getRegions(), which does the same without reflection.

**Comment by mewin** [comment]
Its weird how I dont receive a mail when a new issue is opened but I do when someone comments on this issue. In fact there are versions for WG 6 (which are pretty much just recompiled) on http://ci.mewin.de . And thank you for your advices, if you made a pull request I'd pretty likely accept it.
